/* Generated by AN DISI Unibo */ 
package it.unibo.sonarmanager

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarmanager ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val DFREE = 30
				var guasto = false
				var counterError = 0
				var counterDeposit = 0
				var doDepositSent = false
				var deposit = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(3000) 
						CommUtils.outcyan("$name : starting")
						subscribeToLocalActor("sonar") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
				state("listen_for_measurement") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0",targetState="process",cond=whenEvent("measurement"))
					transition(edgeName="t1",targetState="checkForDeposit",cond=whenEvent("waitingForDeposit"))
					transition(edgeName="t2",targetState="stopWaitingDeposit",cond=whenEvent("stopWaitingForDeposit"))
				}	 
				state("process") { //this:State
					action { //it:State
						 var M = -1  
						if( checkMsgContent( Term.createTerm("measurement(CM)"), Term.createTerm("measurement(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												M = payloadArg(0).toInt()
						}
						if(  M < DFREE/2  
						 ){CommUtils.outcyan("$name container presente")
						
										counterError = 0
										counterDeposit += 1
						if(  deposit && counterDeposit >= 3 && !doDepositSent  
						 ){CommUtils.outgreen("$name invio deposito")
						emit("doDeposit", "doDeposit(1)" ) 
						 doDepositSent = true  
						}
						}
						if(  M >= DFREE/2 && M <= DFREE  
						 ){CommUtils.outcyan("$name container assente")
						
										counterError = 0
										counterDeposit = 0
										doDepositSent = false
						}
						if(  M > DFREE  
						 ){CommUtils.outred("$name possibile guasto")
						
										counterError += 1
										counterDeposit = 0
										doDepositSent = false
						}
						if(  counterError >= 3 && !guasto  
						 ){CommUtils.outred("$name GUASTO")
						 
										guasto = true 
						emit("sonaralert", "sonaralert(1)" ) 
						}
						else
						 {if(  guasto && counterError < 3  
						  ){CommUtils.outyellow("$name GUASTO RIENTRATO")
						  guasto = false  
						 emit("sonarok", "sonarok(1)" ) 
						 }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
				state("checkForDeposit") { //this:State
					action { //it:State
						deposit = true  
						CommUtils.outcyan("$name checking for deposit")
						if(  counterDeposit >= 3  
						 ){CommUtils.outgreen("$name invio deposito")
						 doDepositSent = true  
						emit("doDeposit", "doDeposit(1)" ) 
						}
						else
						 {CommUtils.outcyan("$name deposit NOT confirmed: needing other measurements")
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
				state("stopWaitingDeposit") { //this:State
					action { //it:State
						 deposit = false 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listen_for_measurement", cond=doswitch() )
				}	 
			}
		}
} 
