/* Generated by AN DISI Unibo */ 
package it.unibo.holdmanager

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Holdmanager ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outgreen("HoldManager STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("HoldManager IDLE...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="checkProduct",cond=whenRequest("control_product"))
				}	 
				state("checkProduct") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("control_product(PID)"), Term.createTerm("control_product(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("HoldManager checking product ${payloadArg(0)}")
								 val pid = payloadArg(0)  
								request("getProduct", "product(pid)" ,"mock_productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="processProductInfo",cond=whenReply("getProductAnswer"))
				}	 
				state("processProductInfo") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getProductAnswer(JSONSTRING)"), Term.createTerm("product(JSONSTRING)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("HoldManager received product info: ${payloadArg(0)}")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
