/* Generated by AN DISI Unibo */ 
package it.unibo.mockuser

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Mockuser ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var ERROR = false;
				var COUNTLOADS = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(100) 
						CommUtils.outcyan("$name : starting")
						CommUtils.outcyan("$name : loading productservice db")
						 
									val JsonObj1 = "'{\"productId\":1,\"name\":\"p1\",\"weight\":10}'" 
									val JsonObj2 = "'{\"productId\":2,\"name\":\"p2\",\"weight\":20}'" 
									val JsonObj3 = "'{\"productId\":3,\"name\":\"p3\",\"weight\":30}'" 
									val JsonObj4 = "'{\"productId\":4,\"name\":\"p4\",\"weight\":40}'" 
									val JsonObj5 = "'{\"productId\":5,\"name\":\"p5\",\"weight\":200}'" 
						request("createProduct", "product($JsonObj1)" ,"productservice" )  
						request("createProduct", "product($JsonObj2)" ,"productservice" )  
						request("createProduct", "product($JsonObj3)" ,"productservice" )  
						request("createProduct", "product($JsonObj4)" ,"productservice" )  
						request("createProduct", "product($JsonObj5)" ,"productservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
