/* Generated by AN DISI Unibo */ 
package it.unibo.webguiobserver

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Webguiobserver ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 var CurrentState = {}  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(2000) 
						CommUtils.outyellow("$name | START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0",targetState="handleholdupdate",cond=whenEvent("holdupdated"))
					transition(edgeName="t1",targetState="handleholdupdate",cond=whenEvent("productloaded"))
				}	 
				state("handleholdupdate") { //this:State
					action { //it:State
						CommUtils.outblack("$name : updating")
						if( checkMsgContent( Term.createTerm("holdupdated(JSONSTATE)"), Term.createTerm("holdupdated(JSONSTATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            val holdstate = payloadArg(0)
								CommUtils.outyellow("$name : hold updated - $holdstate")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
