services:
  cargoserviceqak:
    container_name: cargoserviceqak
    #image: cargoserviceqak:1.0
    image: docker.io/natbodocker/cargoserviceqak:1.0
    environment:
      - MONGO_HOST=mongodb
      - SERVICE_IP=127.0.0.1
    ports:
      - 8111:8111/tcp
      - 8111:8111/udp
    networks:
      - cargoservice-network

networks:
  cargoservice-network:
    external: true
## docker-compose -f cargoserviceqak.yaml  up
## yamls> docker network ls
## docker network create cargoservice-network
## docker network rm xxx
